version: '3.8'

volumes:
  repos:
  cache:

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - repos:/repos
      - cache:/cache
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
